version: '3.7'
services:
  postgres-offerua:
    container_name: postgres-offerua
    image: postgres:16
    environment:
      POSTGRES_DB: offerua
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./postgres-offerua:/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped

  redis-token-store:
    image: redis
    ports:
        - "6379:6379"
    restart: unless-stopped

  rabbit-mq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: username
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elasticsearch-container
    environment:
      - discovery.type=single-node
      - cluster.name=product_index
    ports:
      - "9200:9200"


#  spring-app:
#    build: .
#    depends_on:
#      - redis
#      - elasticsearch
#    ports:
#      - "8080:8080"
#    command: "./wait-for-it.sh elasticsearch:9200 -- mvn spring-boot:run" //should wait till elastic start