version: '3.7'
services:
  postgres-offerua:
    container_name: postgres-offerua
    image: postgres:16
    environment:
      POSTGRES_DB: offerua
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./postgres-offerua:/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped

  redis-token-store:
    image: redis
    ports:
        - "6379:6379"
    restart: unless-stopped

  rabbit-mq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
