spring:
  redis:
    host: localhost
    port: 6379
  application:
    name: offerua
  datasource:
    url: jdbc:postgresql://localhost:5433/offerua
    username: ${postgres-username}
    password: ${postgres-password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.data.r2dbc: DEBUG
app:
  security:
    jwt:
      secret: ${jwt-secret}
      issuer: http://localhost:8080
      expiresIn: 60m
    refresh:
      expiresIn: 7d
